import { Component } from '@angular/core';

@Component({
  selector: 'app-list-prices-car',
  templateUrl: './list-prices-car.component.html',
  styleUrls: ['./list-prices-car.component.scss']
})
export class ListPricesCarComponent {

  accordionItems: any = [
    { title: 'Taxi', content: [
      { nombre: 'Lavado', precio: 15, color: '#FFFFFF' },
      { nombre: 'Lavado + abajo', precio: 20, color: '#000000', text: '#FFFFFF' },
      { nombre: 'Lavado + motor', precio: 20, color: '#FDD04E' },
      { nombre: 'Lavado general', precio: 30, color: '#000000', text: '#FFFFFF' },
      { nombre: 'Cera a mano', precio: 20, color: '#FDD04E' },
      { nombre: 'Cera a maquina', precio: 30, color: '#FFFFFF' },
      { nombre: 'Motor a vapor', precio: 35, color: '#000000', text: '#FFFFFF' },
      { nombre: 'Desinfección A/A a vapor', precio: 25, color: '#FDD04E' },
      { nombre: 'Limpieza de farolas', precio: 40,  color: '#000000', text: '#FFFFFF'},
      { nombre: 'Hidratación cuero', precio: 10, color: '#FFFFFF' },
      { nombre: 'Hidratación partes negras', precio: 10, color: '#FDD04E'},
      { nombre: 'Exceso de barro', precio: 5, color: '#FFFFFF'  },
      { nombre: 'Aspirada', precio: 10, color: '#FFFFFF' },
      { nombre: 'Polichada moto', precio: '', color: '#FDD04E' },
      { nombre: 'Over haul', precio: 200, color: '#FDD04E' },
      { nombre: 'Polichada', precio: 150, color: '#FDD04E' },
      { nombre: 'Limpieza cojineria', precio: 100, color: '#000000', text: '#FFFFFF'  },
      { nombre: 'Alfombras', precio: 60, color: '#FFFFFF' },
      { nombre: 'Combo 1', precio: 70, color: '#000000', combo: '(Gral + cera a mano + grafito)', text: '#FFFFFF' },
      { nombre: 'Combo 2', precio: 100, color: '#000000', combo: '(Lavado Gral + motor a vapor + cera a maquina)', text: '#FFFFFF' },
      { nombre: 'Combo 3', precio: 350, color: '#000000', combo: '(Polichada+ Overhaul+motor a vapor)', text: '#FFFFFF' },
    ],
    expanded: false
    },
    { title: 'Automovil', content: [
        { nombre: 'Lavado', precio: 15, color: '#FFFFFF' },
        { nombre: 'Lavado + abajo', precio: 20, color: '#000000', text: '#FFFFFF' },
        { nombre: 'Lavado + motor', precio: 15, color: '#FDD04E' },
        { nombre: 'Lavado general', precio: 15, color: '#000000', text: '#FFFFFF' },
        { nombre: 'Cera a mano', precio: 15, color: '#FDD04E' },
        { nombre: 'Cera a maquina', precio: 15, color: '#FFFFFF' },
        { nombre: 'Motor a vapor', precio: 15, color: '#000000', text: '#FFFFFF' },
        { nombre: 'Desinfección A/A a vapor', precio: 15, color: '#FDD04E' },
        { nombre: 'Limpieza de farolas', precio: 15,  color: '#000000', text: '#FFFFFF'},
        { nombre: 'Hidratación cuero', precio: 15, color: '#FFFFFF' },
        { nombre: 'Hidratación partes negras', precio: 15, color: '#FDD04E'},
        { nombre: 'Exceso de barro', precio: 15, color: '#FFFFFF'  },
        { nombre: 'Aspirada', precio: 15, color: '#FFFFFF' },
        { nombre: 'Polichada moto', precio: 15, color: '#FDD04E' },
        { nombre: 'Over haul', precio: 15, color: '#FDD04E' },
        { nombre: 'Polichada', precio: 15, color: '#FDD04E' },
        { nombre: 'Limpieza cojineria', precio: 15, color: '#000000', text: '#FFFFFF'  },
        { nombre: 'Alfombras', precio: 15, color: '#FFFFFF' },
        { nombre: 'Combo 1', precio: 15, color: '#000000', combo: '(Gral + cera a mano + grafito)', text: '#FFFFFF' },
        { nombre: 'Combo 2', precio: 15, color: '#000000', combo: '(Lavado Gral + motor a vapor + cera a maquina)', text: '#FFFFFF' },
        { nombre: 'Combo 3', precio: 15, color: '#000000', combo: '(Polichada+ Overhaul+motor a vapor)', text: '#FFFFFF' },
      ],
      expanded: false
    },
    { title: 'Camioneta', content: [
        { nombre: 'Lavado', precio: 15, color: '#FFFFFF' },
        { nombre: 'Lavado + abajo', precio: 20, color: '#000000', text: '#FFFFFF' },
        { nombre: 'Lavado + motor', precio: 15, color: '#FDD04E' },
        { nombre: 'Lavado general', precio: 15, color: '#000000', text: '#FFFFFF' },
        { nombre: 'Cera a mano', precio: 15, color: '#FDD04E' },
        { nombre: 'Cera a maquina', precio: 15, color: '#FFFFFF' },
        { nombre: 'Motor a vapor', precio: 15, color: '#000000', text: '#FFFFFF' },
        { nombre: 'Desinfección A/A a vapor', precio: 15, color: '#FDD04E' },
        { nombre: 'Limpieza de farolas', precio: 15,  color: '#000000', text: '#FFFFFF'},
        { nombre: 'Hidratación cuero', precio: 15, color: '#FFFFFF' },
        { nombre: 'Hidratación partes negras', precio: 15, color: '#FDD04E'},
        { nombre: 'Exceso de barro', precio: 15, color: '#FFFFFF'  },
        { nombre: 'Aspirada', precio: 15, color: '#FFFFFF' },
        { nombre: 'Polichada moto', precio: 15, color: '#FDD04E' },
        { nombre: 'Over haul', precio: 15, color: '#FDD04E' },
        { nombre: 'Polichada', precio: 15, color: '#FDD04E' },
        { nombre: 'Limpieza cojineria', precio: 15, color: '#000000', text: '#FFFFFF'  },
        { nombre: 'Alfombras', precio: 15, color: '#FFFFFF' },
        { nombre: 'Combo 1', precio: 15, color: '#000000', combo: '(Gral + cera a mano + grafito)', text: '#FFFFFF' },
        { nombre: 'Combo 2', precio: 15, color: '#000000', combo: '(Lavado Gral + motor a vapor + cera a maquina)', text: '#FFFFFF' },
        { nombre: 'Combo 3', precio: 15, color: '#000000', combo: '(Polichada+ Overhaul+motor a vapor)', text: '#FFFFFF' },
    ],
      expanded: false
    },
    { title: 'Camioneta gra', content: [{ nombre: 'Lavado', precio: 15, color: '#FFFFFF' },
        { nombre: 'Lavado', precio: 15, color: '#FFFFFF' },
        { nombre: 'Lavado + abajo', precio: 20, color: '#000000', text: '#FFFFFF' },
        { nombre: 'Lavado + motor', precio: 15, color: '#FDD04E' },
        { nombre: 'Lavado general', precio: 15, color: '#000000', text: '#FFFFFF' },
        { nombre: 'Cera a mano', precio: 15, color: '#FDD04E' },
        { nombre: 'Cera a maquina', precio: 15, color: '#FFFFFF' },
        { nombre: 'Motor a vapor', precio: 15, color: '#000000', text: '#FFFFFF' },
        { nombre: 'Desinfección A/A a vapor', precio: 15, color: '#FDD04E' },
        { nombre: 'Limpieza de farolas', precio: 15,  color: '#000000', text: '#FFFFFF'},
        { nombre: 'Hidratación cuero', precio: 15, color: '#FFFFFF' },
        { nombre: 'Hidratación partes negras', precio: 15, color: '#FDD04E'},
        { nombre: 'Exceso de barro', precio: 15, color: '#FFFFFF'  },
        { nombre: 'Aspirada', precio: 15, color: '#FFFFFF' },
        { nombre: 'Polichada moto', precio: 15, color: '#FDD04E' },
        { nombre: 'Over haul', precio: 15, color: '#FDD04E' },
        { nombre: 'Polichada', precio: 15, color: '#FDD04E' },
        { nombre: 'Limpieza cojineria', precio: 15, color: '#000000', text: '#FFFFFF'  },
        { nombre: 'Alfombras', precio: 15, color: '#FFFFFF' },
        { nombre: 'Combo 1', precio: 15, color: '#000000', combo: '(Gral + cera a mano + grafito)', text: '#FFFFFF' },
        { nombre: 'Combo 2', precio: 15, color: '#000000', combo: '(Lavado Gral + motor a vapor + cera a maquina)', text: '#FFFFFF' },
        { nombre: 'Combo 3', precio: 15, color: '#000000', combo: '(Polichada+ Overhaul+motor a vapor)', text: '#FFFFFF' },
    ],
      expanded: false
    },
    { title: 'Buseta', content: [{ nombre: 'Lavado', precio: 15, color: '#FFFFFF' },
        { nombre: 'Lavado', precio: 15, color: '#FFFFFF' },
        { nombre: 'Lavado + abajo', precio: 20, color: '#000000', text: '#FFFFFF' },
        { nombre: 'Lavado + motor', precio: 15, color: '#FDD04E' },
        { nombre: 'Lavado general', precio: 15, color: '#000000', text: '#FFFFFF' },
        { nombre: 'Cera a mano', precio: 15, color: '#FDD04E' },
        { nombre: 'Cera a maquina', precio: 15, color: '#FFFFFF' },
        { nombre: 'Motor a vapor', precio: 15, color: '#000000', text: '#FFFFFF' },
        { nombre: 'Desinfección A/A a vapor', precio: 15, color: '#FDD04E' },
        { nombre: 'Limpieza de farolas', precio: 15,  color: '#000000', text: '#FFFFFF'},
        { nombre: 'Hidratación cuero', precio: 15, color: '#FFFFFF' },
        { nombre: 'Hidratación partes negras', precio: 15, color: '#FDD04E'},
        { nombre: 'Exceso de barro', precio: 15, color: '#FFFFFF'  },
        { nombre: 'Aspirada', precio: 15, color: '#FFFFFF' },
        { nombre: 'Polichada moto', precio: 15, color: '#FDD04E' },
        { nombre: 'Over haul', precio: 15, color: '#FDD04E' },
        { nombre: 'Polichada', precio: 15, color: '#FDD04E' },
        { nombre: 'Limpieza cojineria', precio: 15, color: '#000000', text: '#FFFFFF'  },
        { nombre: 'Alfombras', precio: 15, color: '#FFFFFF' },
        { nombre: 'Combo 1', precio: 15, color: '#000000', combo: '(Gral + cera a mano + grafito)', text: '#FFFFFF' },
        { nombre: 'Combo 2', precio: 15, color: '#000000', combo: '(Lavado Gral + motor a vapor + cera a maquina)', text: '#FFFFFF' },
        { nombre: 'Combo 3', precio: 15, color: '#000000', combo: '(Polichada+ Overhaul+motor a vapor)', text: '#FFFFFF' },
      ],
    expanded: false },
    { title: 'Furgón peq', content: [{ nombre: 'Lavado', precio: 15, color: '#FFFFFF' },
        { nombre: 'Lavado', precio: 15, color: '#FFFFFF' },
        { nombre: 'Lavado + abajo', precio: 20, color: '#000000', text: '#FFFFFF' },
        { nombre: 'Lavado + motor', precio: 15, color: '#FDD04E' },
        { nombre: 'Lavado general', precio: 15, color: '#000000', text: '#FFFFFF' },
        { nombre: 'Cera a mano', precio: 15, color: '#FDD04E' },
        { nombre: 'Cera a maquina', precio: 15, color: '#FFFFFF' },
        { nombre: 'Motor a vapor', precio: 15, color: '#000000', text: '#FFFFFF' },
        { nombre: 'Desinfección A/A a vapor', precio: 15, color: '#FDD04E' },
        { nombre: 'Limpieza de farolas', precio: 15,  color: '#000000', text: '#FFFFFF'},
        { nombre: 'Hidratación cuero', precio: 15, color: '#FFFFFF' },
        { nombre: 'Hidratación partes negras', precio: 15, color: '#FDD04E'},
        { nombre: 'Exceso de barro', precio: 15, color: '#FFFFFF'  },
        { nombre: 'Aspirada', precio: 15, color: '#FFFFFF' },
        { nombre: 'Polichada moto', precio: 15, color: '#FDD04E' },
        { nombre: 'Over haul', precio: 15, color: '#FDD04E' },
        { nombre: 'Polichada', precio: 15, color: '#FDD04E' },
        { nombre: 'Limpieza cojineria', precio: 15, color: '#000000', text: '#FFFFFF'  },
        { nombre: 'Alfombras', precio: 15, color: '#FFFFFF' },
        { nombre: 'Combo 1', precio: 15, color: '#000000', combo: '(Gral + cera a mano + grafito)', text: '#FFFFFF' },
        { nombre: 'Combo 2', precio: 15, color: '#000000', combo: '(Lavado Gral + motor a vapor + cera a maquina)', text: '#FFFFFF' },
        { nombre: 'Combo 3', precio: 15, color: '#000000', combo: '(Polichada+ Overhaul+motor a vapor)', text: '#FFFFFF' },
      ],
    expanded: false },
    { title: 'Furgón gra', content: [{ nombre: 'Lavado', precio: 15, color: '#FFFFFF' },
        { nombre: 'Lavado', precio: 15, color: '#FFFFFF' },
        { nombre: 'Lavado + abajo', precio: 20, color: '#000000', text: '#FFFFFF' },
        { nombre: 'Lavado + motor', precio: 15, color: '#FDD04E' },
        { nombre: 'Lavado general', precio: 15, color: '#000000', text: '#FFFFFF' },
        { nombre: 'Cera a mano', precio: 15, color: '#FDD04E' },
        { nombre: 'Cera a maquina', precio: 15, color: '#FFFFFF' },
        { nombre: 'Motor a vapor', precio: 15, color: '#000000', text: '#FFFFFF' },
        { nombre: 'Desinfección A/A a vapor', precio: 15, color: '#FDD04E' },
        { nombre: 'Limpieza de farolas', precio: 15,  color: '#000000', text: '#FFFFFF'},
        { nombre: 'Hidratación cuero', precio: 15, color: '#FFFFFF' },
        { nombre: 'Hidratación partes negras', precio: 15, color: '#FDD04E'},
        { nombre: 'Exceso de barro', precio: 15, color: '#FFFFFF'  },
        { nombre: 'Aspirada', precio: 15, color: '#FFFFFF' },
        { nombre: 'Polichada moto', precio: 15, color: '#FDD04E' },
        { nombre: 'Over haul', precio: 15, color: '#FDD04E' },
        { nombre: 'Polichada', precio: 15, color: '#FDD04E' },
        { nombre: 'Limpieza cojineria', precio: 15, color: '#000000', text: '#FFFFFF'  },
        { nombre: 'Alfombras', precio: 15, color: '#FFFFFF' },
        { nombre: 'Combo 1', precio: 15, color: '#000000', combo: '(Gral + cera a mano + grafito)', text: '#FFFFFF' },
        { nombre: 'Combo 2', precio: 15, color: '#000000', combo: '(Lavado Gral + motor a vapor + cera a maquina)', text: '#FFFFFF' },
        { nombre: 'Combo 3', precio: 15, color: '#000000', combo: '(Polichada+ Overhaul+motor a vapor)', text: '#FFFFFF' },
    ],
      expanded: false
    },
    { title: 'Motos', content: [{ nombre: 'Lavado', precio: 15, color: '#FFFFFF' },
        { nombre: 'Lavado', precio: 15, color: '#FFFFFF' },
        { nombre: 'Lavado + abajo', precio: 20, color: '#000000', text: '#FFFFFF' },
        { nombre: 'Lavado + motor', precio: 15, color: '#FDD04E' },
        { nombre: 'Lavado general', precio: 15, color: '#000000', text: '#FFFFFF' },
        { nombre: 'Cera a mano', precio: 15, color: '#FDD04E' },
        { nombre: 'Cera a maquina', precio: 15, color: '#FFFFFF' },
        { nombre: 'Motor a vapor', precio: 15, color: '#000000', text: '#FFFFFF' },
        { nombre: 'Desinfección A/A a vapor', precio: 15, color: '#FDD04E' },
        { nombre: 'Limpieza de farolas', precio: 15,  color: '#000000', text: '#FFFFFF'},
        { nombre: 'Hidratación cuero', precio: 15, color: '#FFFFFF' },
        { nombre: 'Hidratación partes negras', precio: 15, color: '#FDD04E'},
        { nombre: 'Exceso de barro', precio: 15, color: '#FFFFFF'  },
        { nombre: 'Aspirada', precio: 15, color: '#FFFFFF' },
        { nombre: 'Polichada moto', precio: 15, color: '#FDD04E' },
        { nombre: 'Over haul', precio: 15, color: '#FDD04E' },
        { nombre: 'Polichada', precio: 15, color: '#FDD04E' },
        { nombre: 'Limpieza cojineria', precio: 15, color: '#000000', text: '#FFFFFF'  },
        { nombre: 'Alfombras', precio: 15, color: '#FFFFFF' },
        { nombre: 'Combo 1', precio: 15, color: '#000000', combo: '(Gral + cera a mano + grafito)', text: '#FFFFFF' },
        { nombre: 'Combo 2', precio: 15, color: '#000000', combo: '(Lavado Gral + motor a vapor + cera a maquina)', text: '#FFFFFF' },
        { nombre: 'Combo 3', precio: 15, color: '#000000', combo: '(Polichada+ Overhaul+motor a vapor)', text: '#FFFFFF' },
      ],
      expanded: false
    },
  ];

  toggleAccordionItem(index: number): void {
    this.accordionItems[index].expanded = !this.accordionItems[index].expanded;
  }

}
